[tool.poetry]
name = "lära sig python"
version = "0.1.0"
description = ""
authors = ["Vilhelm von Ehrenheim <vilhelm@qa.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
